name: Lint

on: [push, pull_request]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: debug
        run: |
          which pip
          which python
          pip --version
          python --version

      - uses: ichard26/black@feature/allow-overriding-black-version-in-github-action
        with:
          options: "--diff --check --color -v"
          src: "."

      - uses: ichard26/black@feature/allow-overriding-black-version-in-github-action
        with:
          options: "--diff --check --color -v"
          src: "."
          version: "19.10b0"

      - name: more debug
        run: python -c "import pathspec ; print(pathspec.__file__) ; print(pathspec.__version__)"
