name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: debug
        run: |
          which pip
          which python
          pip --version
          python --version
      - uses: stefanfoulis/black@feature/allow-overriding-black-version-in-github-action
        with:
          black_args: ". --diff --exclude *.py"
      - name: more debug
        run: python -c "import pathspec ; print(pathspec.__file__) ; print(pathspec.__version__)"
