name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: debug
        run: |
          which pip
          which python
          pip --version
          python --version
      - uses: stefanfoulis/black@feature/allow-overriding-black-version-in-github-action
        with:
          black_args: ". --diff --exclude /(folder1/folder2)/"
          black_version: "19.10b0"
