name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - uses: stefanfoulis/black@allow-overriding-black-version-in-github-action
        with:
          black_args: ". --diff --exclude /(folder1/folder2)/"
